name: Deploy to dev
run-name: Deploy `${{ github.head_ref || github.ref_name }}` to `${{ env.WPE_ENV }}`

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      ENVIRONMENT: development
      # Add WPE environment name here
      WPE_ENV:

    steps:
      # Get Build Repository
      - name: Check out build branch
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      # Composer install
      - name: 'Composer install'
        uses: ./.github/actions/composer-install
        with:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          OP_VAULT: ${{ secrets.OP_VAULT }}
          OP_ITEM: ${{ secrets.OP_ITEM }}

      # Set up node version
      - name: Set up node
        uses: actions/setup-node@v6
        with:
          node-version-file: "./.nvmrc"
          cache: 'npm'
          check-latest: true

      # NPM install all dependencies and build assets
      - name: NPM install and build assets
        run: |
          npm install
          npm run dist

      # NPM install production dependencies
      - name: NPM install production dependencies
        run: npm install --omit=dev --omit=optional

      ##########
      ### DEPLOY: Use the WPE git deploy hook method. TLDR; rsync our repo on their repo and push.

      - name: Deploy to WP Engine
        uses: wpengine/github-action-wpe-site-deploy@v3
        with:
          WPE_SSHG_KEY_PRIVATE: ${{ secrets.WPE_SSHG_KEY_PRIVATE }}
          WPE_ENV: ${{ env.WPE_ENV }}
          FLAGS: -azvr --inplace --delete --exclude-from=.deploy/deploy-exclude.txt
