name: Deploy to staging
run-name: Deploy `${{ github.head_ref || github.ref_name }}` to `${{ env.WPE_ENV }}`

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

on:
#  push:
#    branches:
#      - server/staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      ENVIRONMENT: staging
      # Add WPE environment name here
      WPE_ENV:

    steps:
      # Get Build Repository
      - name: Check out build branch
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      # Composer install
      - name: 'Composer install'
        uses: ./.github/actions/composer-install
        with:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          OP_VAULT: ${{ secrets.OP_VAULT }}
          OP_ITEM: ${{ secrets.OP_ITEM }}

      # Set up node version
      - name: Set up node
        uses: actions/setup-node@v6
        with:
          node-version-file: "./.nvmrc"
          cache: 'npm'
          check-latest: true

      # NPM install all dependencies and build assets
      - name: NPM install and build assets
        run: |
          npm install
          npm run dist

      # NPM install production dependencies
      - name: NPM install production dependencies
        run: npm install --omit=dev --omit=optional

      # Create local config for environment based settings
      - name: Create local config
        run: |
          php -r "file_exists( 'local-config.php' ) || copy( 'local-config-sample.php', 'local-config.php' );"
          FILE="local-config.php"
          (head -n 1 "$FILE" && printf '// Added by GitHub Actions CI\ndefine( "WP_ENVIRONMENT_TYPE", "%s" );\n\n' "${{ env.ENVIRONMENT }}" && tail -n +2 "$FILE") > "$FILE.tmp" && mv "$FILE.tmp" "$FILE"
          echo "First 8 lines after update:" && head -n 8 "$FILE"

      ##########
      ### DEPLOY: Use the WPE git deploy hook method. TLDR; rsync our repo on their repo and push.

      - name: Deploy to WP Engine
        uses: wpengine/github-action-wpe-site-deploy@v3
        with:
          WPE_SSHG_KEY_PRIVATE: ${{ secrets.WPE_SSHG_KEY_PRIVATE }}
          WPE_ENV: ${{ env.WPE_ENV }}
          FLAGS: -azvr --inplace --delete --exclude-from=.deploy/deploy-exclude.txt
